### PR TITLE
added the suggested folders within src

### LINKED ISSUE #62: Folder Restructuring
Inside our `src/` dir can we move all our script files into `src/scripts/` and the helper functions into `src/helper/`

### PR DESCRIPTION
**Pull request by salva-u**
Added the suggested folder, let me know if you guys wanna do it differently.
Additionally the helper.py file we had previously is now removed. 
Also note, if this is okay with everyone, we need to reference our helper functions in script file using src.helper.<function_name>

### CODE REVIEW

**Comment by rbouwer** [comment]
LGTM - I think including a TOC or tree structure of our directory to indicate for example what folders such as 'helper' contan would be helpful

I will open an issue for updating the README

**Review by atabak-alishiri — APPROVED** [review]

**Review by rbouwer — APPROVED** [review]
LGTM! - as we have discussed, we will make a scripts folder and will therefore need to adjust our scripts to point to helper folder (i.e. add `sys.path.append("..")`)

**Review by farrandi — APPROVED** [review]
LGTM

**Comment by salva-u** [comment]
|-- CODE_OF_CONDUCT.md
|-- CONTRIBUTING.md
|-- Dockerfile
|-- LICENSE.md
|-- README.md
|-- compose.yml
|-- data
|   |-- raw
|   |   `-- train_data.csv
|   `-- sampled_dataset.csv
|-- environment.yml
|-- notebooks
|   |-- english_language_learning_ability_prediction_analysis.ipynb
|   |-- english_language_learning_ability_prediction_analysis.pdf
|   `-- random_sampling_from_full_dataset.ipynb
|-- results
|   |-- figures
|   |   |-- education-level-fig.png
|   |   |-- feat-categoric-figs.png
|   |   |-- feat-correlation-matrix.png
|   |   `-- feat-numeric-figs.png
|   |-- models
|   |   `-- preprocessor
|   |       `-- preprocessor.pkl
|   `-- tables
|       `-- correlation-matrix.csv
|-- src
|   |-- __pycache__
|   |   |-- correlation_matrix.cpython-311.pyc
|   |   |-- correlation_matrix.cpython-39.pyc
|   |   |-- plot_histogram_with_exclusions.cpython-311.pyc
|   |   |-- plot_histogram_with_exclusions.cpython-39.pyc
|   |   |-- plt_regr_pred.cpython-311.pyc
|   |   |-- search_top_models.cpython-311.pyc
|   |   `-- show_feat_coeff.cpython-311.pyc
|   |-- helper
|   |   |-- correlation_matrix.py
|   |   |-- plot_histogram_with_exclusions.py
|   |   |-- plt_regr_pred.py
|   |   |-- search_top_models.py
|   |   `-- show_feat_coeff.py
|   `-- scripts
|       `-- tmp file.py
|-- team_contract.md
`-- tests
    |-- __pycache__
    |   |-- test_correlation_matrix.cpython-311.pyc
    |   `-- test_plot_histogram_with_exclusions.cpython-311.pyc
    |-- helper_test.py
    |-- test-plt_regr_pred.py
    |-- test-show_feat_coeff.py
    |-- test_correlation_matrix.py
    |-- test_plot_histogram_with_exclusions.py
    `-- test_search_top_models.py

**Pull request merged**
