### PR TITLE
added changelogs

### LINKED ISSUE #94: Logging Changes Made
Docker:
1. Uploaded to docker hub 
2. Instead of manual conda install --> we use conda environment conda file 

Helper Functions:
1. Fix `show_feat_coeff.py` and `plot_regr_pred.py` functions and corresponding test files:
    plot_regr_pred: 402094b8f906e4f92f0cd9ec749b27f19481eafd
        -Fixed return to be Axes object and added unittest rather than pytest
    show_feat_coeff: b9a06f5875ca940933eeb148d9a5aa6dd6568d55
        -Fixed return to get feature names out from X_train rather than X_enc and added unittest rather than pytest
        -Also adjusted parameters for FunctionTransformer (feature_names_out='one-to-one") so that we could get all feature names

Data Download and EDA:
1. We fixed dropping of some additional question level columns that wouldn't be used in the analysis but were being dropped outside the transformer. 
2.

### PR DESCRIPTION
**Pull request by salva-u**
PR open to add to it. Not ready for merging

### CODE REVIEW

**Comment by salva-u** [comment]
added all changes expect the ones @rbouwer is currently making

**Comment by rbouwer** [comment]
Added my improvements to change log - LGTM

**Review by farrandi — APPROVED** [review]
Added mine too!

**Review by rbouwer — APPROVED** [review]
LGTM!

**Review by atabak-alishiri — APPROVED** [review]

**Pull request merged**
