### PR TITLE
Plotting & Coefficient Interpretation Function & Tests

### LINKED ISSUE #41: Plotting & Coefficient Interpretation Function
create function and test as per https://github.com/ttimbers/demo-tests-ds-analysis-python example

### PR DESCRIPTION
**Pull request by rbouwer**
~~NOT READY FOR MERGE (opening PR for visibility)~~ Update: ready for review (added reviewers)

- added coefficient interpretation function to src and test to tests
- added plotting function to src and test to tests

### CODE REVIEW

**Comment by rbouwer** [comment]
Still need to add tests

**Comment by salva-u** [comment]
I may be wrong but the tests folder does not show the files `tests/test-plt_regr_pred` and `tests/test-show_feat_coeff` as .py files

**Comment by rbouwer** [comment]
> I may be wrong but the tests folder does not show the files `tests/test-plt_regr_pred` and `tests/test-show_feat_coeff` as .py files

oh weird - I'll check and try and fix that

**Review by farrandi — APPROVED** [review]
LGTM, 

nit: normally for (python) files, you add a new empty line at the end.

**Review by atabak-alishiri — APPROVED** [review]

**Review by salva-u — APPROVED** [review]

**Pull request merged**
