### PR TITLE
8 laso model tuning

### LINKED ISSUE #8: Lasso Model Tuning
- Choose the hyperparameters via randomsearch
- Train and score
- Analyze the results

### PR DESCRIPTION
**Pull request by rbouwer**
NOT READY FOR MERGE TO MAIN (need to coordinate with @farrandi with Ridge section)

- Added Lasso Regression section at bottom of Notebook
- Will adjust wording around Lasso modelling based on Ridge comparison
- When choose best model, need to decide what bits of analysis to keep for both vs one

### CODE REVIEW

**Review by farrandi — COMMENTED** [review]
Seems good, I did write my part for Ridge and it seems like some of the important coefficients are similar.

We can maybe make a section about it in this branch.

I am thinking of the steps to be:

1. Approve and merge "Ridge"
2. Rebase main to this branch
3. Write the conclusion based on both
4. Approve and merge this PR

**Comment by farrandi** [comment]
nit: I added a table showing the top 5 models from the RandomSearchCV, so you can add that too.

But we do not need to add it.

**Comment by rbouwer** [comment]
> Seems good, I did write my part for Ridge and it seems like some of the important coefficients are similar.
> 
> We can maybe make a section about it in this branch.
> 
> I am thinking of the steps to be:
> 
> 1. Approve and merge "Ridge"
> 2. Rebase main to this branch
> 3. Write the conclusion based on both
> 4. Approve and merge this PR

Hey @farrandi - as per our discussion on slack, I moved the coefficient section to the discussion and made the Ridge changes accordingly in your Ridge branch, added to the conclusion.

@salva-u @atabak-alishiri if Ridge and Lasso (branches 8 & 21) look okay with you guys (note: Lasso branch has the discussion and conclusion in it since it was the better performing model) then we can merge it?

**Review by atabak-alishiri — APPROVED** [review]

**Comment by salva-u** [comment]
- Discussed together that Lasso model performs better ( same as nando's branch add r2 score )
- Will make improvements alongside rigde improvements on new branch

**Review by salva-u — APPROVED** [review]

**Pull request merged**
