### PR TITLE
34 make dockerfile

### LINKED ISSUE #34: Make dockerfile

### PR DESCRIPTION
**Pull request by farrandi**
NOT DONE YET.

Making PR because running into a problem:
- Unable to `conda install` vegafusion...

Getting error:
```
Channels:
 - conda-forge
Platform: linux-aarch64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested vegafusion-python-embed
  - nothing provides vegafusion-python-embed needed by vegafusion-0.0.4-pyhd8ed1ab_0
  - nothing provides vegafusion-python-embed needed by vegafusion-0.0.4-pyhd8ed1ab_0

Could not solve for environment specs
The following packages are incompatible
├─ vegafusion is not installable because there are no viable options
│  ├─ vegafusion [0.0.4|0.1.0|...|0.9.0] would require
│  │  └─ vegafusion-python-embed, which does not exist (perhaps a missing channel);
│  └─ vegafusion [1.0.1|1.0.2|...|1.4.5] would require
│     └─ vegafusion-python-embed >=1.0 , which does not exist (perhaps a missing channel);
├─ vegafusion-jupyter is not installable because there are no viable options
│  ├─ vegafusion-jupyter [0.0.4.post1|0.1.0|...|0.9.0] would require
│  │  └─ vegafusion, which cannot be installed (as previously explained);
│  └─ vegafusion-jupyter [1.0.1|1.0.2|...|1.4.5] would require
│     └─ vegafusion >=1.0 , which cannot be installed (as previously explained);
└─ vegafusion-python-embed does not exist (perhaps a typo or a missing channel).
```

### CODE REVIEW

**Comment by farrandi** [comment]
Solved the issue by installing vegafusion using `pip install` instead of conda. 

- Add the dockerfile
- Add the compose.yml
- Update readme for installation instructions

**Comment by farrandi** [comment]
DONE now.

Requesting review.

**Comment by salva-u** [comment]
Do we have the github workflow set up as well?

**Comment by farrandi** [comment]
> Do we have the github workflow set up as well?

Made a new PR for it #45

**Comment by salva-u** [comment]
I am not sure but are we supposed to include downloading jupyter lab/notebook etc as well in the dockerfile  or just whatever is in our env file.
Sth like this: 
FROM continuumio/miniconda3

# Install Jupyter, JupterLab, R & the IRkernel
RUN conda install -y --quiet \
    jupyter \
    jupyterlab=3.* \
    r-base=4.1.* \
    r-irkernel

**Comment by farrandi** [comment]
Since I am using the minimal_notebook image as a base, we actually do not need to install jupyter again but I am simply adding it to match the `environment.yml` file we have. I tried it manually in the container terminal and if it exists it will simply say "already installed".

**Review by salva-u — APPROVED** [review]

**Review by atabak-alishiri — APPROVED** [review]

**Review by rbouwer — APPROVED** [review]
LGTM!

**Pull request merged**
