### PR TITLE
93 create makefile

### LINKED ISSUE #93: Create Makefile

### PR DESCRIPTION
**Pull request by farrandi**

### CODE REVIEW

**Review by rbouwer — APPROVED** [review]
LGTM!

**Comment by salva-u** [comment]
works, LGTM

**Review by salva-u — APPROVED** [review]

**Comment by salva-u** [comment]
I was just looking at Tiff's example in the she has some code to add .nojekyll automatically, could you add that in:
	jupyter-book build report
	cp -r report/_build/html/* docs
	if [ ! -f ".nojekyll" ]; then touch docs/.nojekyll; fi

**Review by salva-u — CHANGES_REQUESTED** [review]
https://github.com/ttimbers/breast_cancer_predictor_py/blob/v3.0.0/Makefile
not sure if we need it but maybe?
	jupyter-book build report
	cp -r report/_build/html/* docs
	if [ ! -f ".nojekyll" ]; then touch docs/.nojekyll; fi

**Review by atabak-alishiri — APPROVED** [review]

**Comment by farrandi** [comment]
Added the command @salva-u suggested at the end of makefile.

Also redid some testing and updated the dockerfile, compose, and readme to the correct instructions.

**Review by salva-u — APPROVED** [review]

**Pull request merged**
