### PR TITLE
46 fixing the transformer dropping outside of transformer

### LINKED ISSUE #46: Fixing the transformer (dropping outside of transformer)
Four lines of code are dropping a few columns before the transformer, we should add them to the drop list of the transformer.

### PR DESCRIPTION
**Pull request by atabak-alishiri**
Please review this one carefully because it is changing the drop list and hence the transformer.

### CODE REVIEW

**Comment by salva-u** [comment]
Added  removed extra columns to Transformation table

**Review by salva-u — APPROVED** [review]

**Review by farrandi — APPROVED** [review]
LGTM

**Comment by rbouwer** [comment]
Will check for numeric eda graphs to be fixed once function is fixed

**Review by rbouwer — APPROVED** [review]

**Comment by salva-u** [comment]
eda numeric graphs will be fixed once we merge the helper function branch

**Pull request merged**
