### PR TITLE
53 replace code chunks in notebook with functions

### LINKED ISSUE #53: Replace Code Chunks in Notebook with Functions
Update as per @rbouwer @farrandi @atabak-alishiri functions (@salva-u already in notebook)

### PR DESCRIPTION
**Pull request by rbouwer**
I updated the imports at the top of the file to include all of our function files

- @salva-u 's function is already in there
- I have added mine two to the bottom 

Right now our branches have not been merged so functions are not working so we can pull the changes once we merge those branches and once we add in the other two functions we can check to make sure everything is ok

### CODE REVIEW

**Comment by salva-u** [comment]
added exclusion of the strange ID and Q_ columns from being passed into correlation matrix function call

**Review by salva-u — APPROVED** [review]

**Comment by farrandi** [comment]
I already:
- added my function to the analysis notebook
- rebased main into the branch
- ran the whole notebook in docker compose and confirmed most of it works


Some problems:
- It seems it failed to run in the discussion cell with the function `show_feat_coeff `, @rbouwer can you give it a look?
- @atabak-alishiri still needs to add his functions to the notebook

**Comment by atabak-alishiri** [comment]
I added the `plot_histogram_with_exclusions` function to our analysis notebook. It should be ready to merge.

**Review by farrandi — APPROVED** [review]

**Review by atabak-alishiri — APPROVED** [review]

**Comment by rbouwer** [comment]
- added "alt.data_transformers.enable("vegafusion")"
- reran notebook (runs successfully)
- rendered pdf
@farrandi @salva-u @atabak-alishiri ready for review for approval

**Review by salva-u — APPROVED** [review]

**Comment by rbouwer** [comment]
made collectively agreed upon README change

**Pull request merged**
