### PR TITLE
Preprocessed Dataset with EDA added + intro

### LINKED ISSUE #7: Preprocess and transform Data
Data loading, preprocessing (EDA),  transformation + Intro

### PR DESCRIPTION
**Pull request by salva-u**
Finished :
- Added the Blue print to be filled for intro - it has some sub sections which we need to add ( perhaps with the model and results it would be more nice to add the summary etc? or we can add it now)
- EDA
- Added appropriate column transformers 
- Added the preprocessor pipeline object 
To be done:
- Finish Intro
- Add check if the transform of the preprocessor behaves as expected when aligned with column names and new columns added by transformers 
- Add any fixes that are needed for model building

### CODE REVIEW

**Comment by salva-u** [comment]
fixed some unexpected issues encountered in the transformer, NA values and also the function transformer was throwing None for most category types - fixes are pushed so we can merge

**Comment by atabak-alishiri** [comment]
I double-checked the code and everything looks fine for now.

**Review by atabak-alishiri — APPROVED** [review]

**Review by farrandi — COMMENTED** [review]
I checkout-ed this branch in my local and found a few things:
- Need to update the environment.yml since altair is not installed there
- Under the EDA section, I see some code blocks with only commented code, might want to remove these

**Comment by salva-u** [comment]
Hi nando, yes let's change the env file tomorrow, maybe during our meeting. For the commented out code, we will remove it later, once the model part for you guys does not need any changes in the EDA/Preprocessing. We will clean it up and add better comments etc.

**Comment by farrandi** [comment]
I added a commit to this branch. It basically updated the environment.yml file.

I installed:
1. Altair
2. Vegafusion
3. Matplotlib

The notebook can now run with the environment.

You guys should update the environment in your local using the commands:
```
conda env remove -n 522
conda env create -f environment.yml
```

**Comment by rbouwer** [comment]
Writing this here (but we can talk about it in our meeting today) - in the Preview of the notebook file, it doesn't show the plot outputs (@farrandi is this linked to not having altair loaded in the environment?) -- can check during our meeting

**Review by farrandi — APPROVED** [review]

**Review by rbouwer — APPROVED** [review]

**Pull request merged**
